"""purchasing returns and ledgers

Revision ID: 0f0fa544f859
Revises: 17bdfd3b3fb0
Create Date: 2026-09-04 10:41:11.434635
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f0fa544f859'
down_revision: Union[str, None] = '17bdfd3b3fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('ledger_type', sa.String(length=20), nullable=False),
    sa.Column('party_type', sa.String(length=20), nullable=True),
    sa.Column('party_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('amount_delta', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('reference_type', sa.String(length=30), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_delta <> 0'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_party_id'), ['party_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index('ix_ledger_org_type_party_time', ['organization_id', 'ledger_type', 'party_id', 'occurred_at'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('order_number', sa.String(length=80), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('total >= 0'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'order_number')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_ordered_at'), ['ordered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index('ix_purchase_org_branch_time', ['organization_id', 'branch_id', 'ordered_at'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0 AND unit_cost >= 0'),
    sa.CheckConstraint('received_quantity >= 0 AND received_quantity <= quantity'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_items_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('sales_returns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('sales_order_id', sa.String(length=36), nullable=False),
    sa.Column('return_number', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'return_number')
    )
    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_returns_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_returned_at'), ['returned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_returns_sales_order_id'), ['sales_order_id'], unique=False)

    op.create_table('refunds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('sales_return_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_return_id'], ['sales_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refunds_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_sales_return_id'), ['sales_return_id'], unique=False)

    op.create_table('sales_return_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('sales_return_id', sa.String(length=36), nullable=False),
    sa.Column('sales_order_item_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('restock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0 AND amount >= 0'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_item_id'], ['sales_order_items.id'], ),
    sa.ForeignKeyConstraint(['sales_return_id'], ['sales_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_return_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_return_items_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_sales_order_item_id'), ['sales_order_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_return_items_sales_return_id'), ['sales_return_id'], unique=False)

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned_quantity', sa.Numeric(precision=14, scale=3), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.drop_column('returned_quantity')

    with op.batch_alter_table('sales_return_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_return_items_sales_return_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_sales_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_sales_return_items_organization_id'))

    op.drop_table('sales_return_items')
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_sales_return_id'))
        batch_op.drop_index(batch_op.f('ix_refunds_organization_id'))

    op.drop_table('refunds')
    with op.batch_alter_table('sales_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_returns_sales_order_id'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_returned_at'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_organization_id'))
        batch_op.drop_index(batch_op.f('ix_sales_returns_branch_id'))

    op.drop_table('sales_returns')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_organization_id'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_org_branch_time')
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_organization_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_ordered_at'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_branch_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_org_type_party_time')
        batch_op.drop_index(batch_op.f('ix_ledger_entries_reference_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_party_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_category'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_branch_id'))

    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
