"""durable import provenance

Revision ID: 1db75e853483
Revises: 0f0fa544f859
Create Date: 2026-09-04 10:43:46.434583
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1db75e853483'
down_revision: Union[str, None] = '0f0fa544f859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_system', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('mapping_json', sa.Text(), nullable=True),
    sa.Column('validation_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'checksum_sha256')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_batches_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_batches_uploaded_by'), ['uploaded_by'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_import_batches_organization_id'))
        batch_op.drop_index(batch_op.f('ix_import_batches_checksum_sha256'))

    op.drop_table('import_batches')
    # ### end Alembic commands ###
