"""add cashier shifts and cash movements

Revision ID: 1ea514a7e2a0
Revises: 66fd0a172453
Create Date: 2026-09-30 23:18:04.555054
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1ea514a7e2a0'
down_revision: Union[str, None] = '66fd0a172453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashier_shifts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('drawer_label', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('opening_cash', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_cash', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('counted_cash', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('variance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cashier_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cashier_shifts_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cashier_shifts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cashier_shifts_user_id'), ['user_id'], unique=False)

    op.create_table('cash_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('shift_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['cashier_shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_movements_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_movements_shift_id'), ['shift_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_shift_id'), ['shift_id'], unique=False)
        batch_op.create_foreign_key('fk_payments_shift_id_cashier_shifts', 'cashier_shifts', ['shift_id'], ['id'])

    # ### end Alembic commands ###

    # Data-only: adds the cash_shortage approval rule for every organization
    # created before this revision that does not already have one. New
    # organizations get it at creation via api.approvals.seed_default_rules.
    import uuid
    from datetime import datetime, timezone

    connection = op.get_bind()
    has_rule = {row[0] for row in connection.execute(
        sa.text("SELECT organization_id FROM approval_rules WHERE kind = 'cash_shortage'"))}
    org_ids = [row[0] for row in connection.execute(sa.text("SELECT id FROM organizations"))]
    now = datetime.now(timezone.utc)
    rules_table = sa.table(
        "approval_rules", sa.column("id", sa.String), sa.column("organization_id", sa.String),
        sa.column("kind", sa.String), sa.column("threshold", sa.Numeric), sa.column("approver_role", sa.String),
        sa.column("active", sa.Boolean), sa.column("created_at", sa.DateTime), sa.column("updated_at", sa.DateTime),
    )
    rows = [
        {
            "id": str(uuid.uuid4()), "organization_id": org_id, "kind": "cash_shortage",
            "threshold": 500, "approver_role": "manager", "active": True, "created_at": now, "updated_at": now,
        }
        for org_id in org_ids if org_id not in has_rule
    ]
    if rows:
        connection.execute(rules_table.insert(), rows)


def downgrade() -> None:
    op.execute("DELETE FROM approval_rules WHERE kind = 'cash_shortage'")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_shift_id_cashier_shifts', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_shift_id'))
        batch_op.drop_column('shift_id')

    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_movements_shift_id'))
        batch_op.drop_index(batch_op.f('ix_cash_movements_organization_id'))

    op.drop_table('cash_movements')
    with op.batch_alter_table('cashier_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cashier_shifts_user_id'))
        batch_op.drop_index(batch_op.f('ix_cashier_shifts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_cashier_shifts_branch_id'))

    op.drop_table('cashier_shifts')
    # ### end Alembic commands ###
