"""accounting engine: accounts and journal

Revision ID: 22338a3dc0df
Revises: 94e975618b25
Create Date: 2026-09-29 07:20:17.854039
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '22338a3dc0df'
down_revision: Union[str, None] = '94e975618b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_organization_id'), ['organization_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('memo', sa.String(length=200), nullable=True),
    sa.Column('reference_type', sa.String(length=30), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index('ix_journal_org_time', ['organization_id', 'occurred_at'], unique=False)

    op.create_table('journal_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('journal_entry_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('party_type', sa.String(length=20), nullable=True),
    sa.Column('party_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0)'),
    sa.CheckConstraint('debit >= 0 AND credit >= 0'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_index('ix_journal_line_account', ['organization_id', 'account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_lines_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_lines_journal_entry_id'), ['journal_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_lines_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_lines_party_id'), ['party_id'], unique=False)

    # ### end Alembic commands ###

    # Data migration: an organization created before this revision has no chart of
    # accounts yet (new ones get one at creation, see api/app_routes.py). Seed the
    # same defaults for every existing one so old orgs post journal entries too.
    import uuid
    from datetime import datetime, timezone

    from api.accounting import DEFAULT_ACCOUNTS

    connection = op.get_bind()
    accounts_table = sa.table(
        "accounts", sa.column("id", sa.String), sa.column("organization_id", sa.String),
        sa.column("code", sa.String), sa.column("name", sa.String), sa.column("type", sa.String),
        sa.column("is_system", sa.Boolean), sa.column("active", sa.Boolean),
        sa.column("created_at", sa.DateTime), sa.column("updated_at", sa.DateTime),
    )
    now = datetime.now(timezone.utc)
    org_ids = [row[0] for row in connection.execute(sa.text("SELECT id FROM organizations"))]
    rows = [
        {
            "id": str(uuid.uuid4()), "organization_id": org_id, "code": code, "name": name,
            "type": type_, "is_system": True, "active": True, "created_at": now, "updated_at": now,
        }
        for org_id in org_ids for code, name, type_ in DEFAULT_ACCOUNTS
    ]
    if rows:
        connection.execute(accounts_table.insert(), rows)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_lines_party_id'))
        batch_op.drop_index(batch_op.f('ix_journal_lines_organization_id'))
        batch_op.drop_index(batch_op.f('ix_journal_lines_journal_entry_id'))
        batch_op.drop_index(batch_op.f('ix_journal_lines_account_id'))
        batch_op.drop_index('ix_journal_line_account')

    op.drop_table('journal_lines')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_journal_org_time')
        batch_op.drop_index(batch_op.f('ix_journal_entries_reference_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_organization_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_branch_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_organization_id'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
