"""loyalty points: rule and entries

Revision ID: 286935c48ab2
Revises: d53fb071825
Create Date: 2026-09-30 16:25:22.036563
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '286935c48ab2'
down_revision: Union[str, None] = 'd53fb071825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('points_per_taka', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('redemption_value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    with op.batch_alter_table('loyalty_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_rules_organization_id'), ['organization_id'], unique=False)

    op.create_table('loyalty_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('points_delta', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('points_delta <> 0'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_entries_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loyalty_entries_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_loyalty_entries_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###

    # Data migration: give every organization that existed before this revision
    # an inactive loyalty rule (a shop that never turns it on keeps selling
    # exactly as before). New organizations get one at creation via
    # api.loyalty.seed_default_rule.
    import uuid
    from datetime import datetime, timezone

    connection = op.get_bind()
    has_rule = {row[0] for row in connection.execute(sa.text("SELECT organization_id FROM loyalty_rules"))}
    org_ids = [row[0] for row in connection.execute(sa.text("SELECT id FROM organizations"))]
    now = datetime.now(timezone.utc)
    rules_table = sa.table(
        "loyalty_rules", sa.column("id", sa.String), sa.column("organization_id", sa.String),
        sa.column("points_per_taka", sa.Numeric), sa.column("redemption_value", sa.Numeric),
        sa.column("active", sa.Boolean), sa.column("created_at", sa.DateTime), sa.column("updated_at", sa.DateTime),
    )
    rows = [
        {
            "id": str(uuid.uuid4()), "organization_id": org_id, "points_per_taka": 100,
            "redemption_value": "0.5", "active": False, "created_at": now, "updated_at": now,
        }
        for org_id in org_ids if org_id not in has_rule
    ]
    if rows:
        connection.execute(rules_table.insert(), rows)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loyalty_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_entries_organization_id'))
        batch_op.drop_index(batch_op.f('ix_loyalty_entries_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_loyalty_entries_customer_id'))

    op.drop_table('loyalty_entries')
    with op.batch_alter_table('loyalty_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_rules_organization_id'))

    op.drop_table('loyalty_rules')
    # ### end Alembic commands ###
