"""platform admin flag on users

Revision ID: 3a9a82752387
Revises: 286935c48ab2
Create Date: 2026-09-30 22:20:04.667871
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a9a82752387'
down_revision: Union[str, None] = '286935c48ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_platform_admin', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_platform_admin')

    # ### end Alembic commands ###
