"""cash closes

Revision ID: 48b004d78129
Revises: a07bdcf9bff0
Create Date: 2026-09-28 16:38:12.599909
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '48b004d78129'
down_revision: Union[str, None] = 'a07bdcf9bff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_closes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('opening_cash', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_cash', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('counted_cash', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('variance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('breakdown_json', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('closed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'branch_id', 'business_date')
    )
    with op.batch_alter_table('cash_closes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_closes_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_closes_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_closes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_closes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_cash_closes_branch_id'))

    op.drop_table('cash_closes')
    # ### end Alembic commands ###
