"""staff setup tokens

Revision ID: 6092b2d8d4cc
Revises: e61a9f46d478
Create Date: 2026-09-28 12:42:34.276937
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6092b2d8d4cc'
down_revision: Union[str, None] = 'e61a9f46d478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setup_token_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('setup_token_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_setup_token_hash'), ['setup_token_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_setup_token_hash'))
        batch_op.drop_column('setup_token_expires_at')
        batch_op.drop_column('setup_token_hash')

    # ### end Alembic commands ###
