"""reorder budget on organization settings

Revision ID: 66fd0a172453
Revises: c8cd4ad93c79
Create Date: 2026-09-30 22:43:13.733894
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '66fd0a172453'
down_revision: Union[str, None] = 'c8cd4ad93c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reorder_budget_bdt', sa.Numeric(precision=14, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization_settings', schema=None) as batch_op:
        batch_op.drop_column('reorder_budget_bdt')

    # ### end Alembic commands ###
