"""shop profile

Revision ID: 97f321479bd6
Revises: 48b004d78129
Create Date: 2026-09-28 17:02:51.321128
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '97f321479bd6'
down_revision: Union[str, None] = '48b004d78129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('vat_reg_no', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('receipt_footer', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('receipt_footer')
        batch_op.drop_column('vat_reg_no')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
