"""batches and expiry

Revision ID: a07bdcf9bff0
Revises: 6092b2d8d4cc
Create Date: 2026-09-28 15:54:34.577294
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a07bdcf9bff0'
down_revision: Union[str, None] = '6092b2d8d4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('batch_no', sa.String(length=80), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('status_reason', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('active','blocked')", name='ck_batch_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'product_id', 'batch_no')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index('ix_batch_org_expiry', ['organization_id', 'expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_product_id'), ['product_id'], unique=False)

    op.create_table('batch_stock',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'batch_id')
    )
    with op.batch_alter_table('batch_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_stock_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_stock_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_stock_organization_id'), ['organization_id'], unique=False)

    op.create_table('sale_item_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('sales_order_item_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('returned_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_order_item_id'], ['sales_order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_item_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_item_batches_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_item_batches_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_item_batches_sales_order_item_id'), ['sales_order_item_id'], unique=False)

    # Plain ADD COLUMN rather than batch mode: on SQLite, batch mode rebuilds the whole
    # table and cannot copy the unnamed CHECK constraints that older tables carry.
    op.add_column('products', sa.Column('track_expiry', sa.Boolean(), server_default=sa.false(), nullable=False))
    if op.get_bind().dialect.name == "sqlite":
        # SQLite adds a foreign-key column in one statement; it has no ADD CONSTRAINT.
        op.execute("ALTER TABLE stock_movements ADD COLUMN batch_id VARCHAR(36) REFERENCES batches (id)")
    else:
        op.add_column('stock_movements', sa.Column('batch_id', sa.String(length=36), nullable=True))
        op.create_foreign_key('fk_stock_movements_batch_id', 'stock_movements', 'batches', ['batch_id'], ['id'])
    op.create_index(op.f('ix_stock_movements_batch_id'), 'stock_movements', ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "sqlite":
        # SQLite cannot drop a foreign-key column, and rebuilding the table fails on the
        # unnamed CHECK constraints of older tables. Roll back a dev database by
        # restoring a backup or recreating it; PostgreSQL rolls back normally.
        raise NotImplementedError("This revision cannot be downgraded on SQLite")
    op.drop_constraint('fk_stock_movements_batch_id', 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_batch_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'batch_id')
    op.drop_column('products', 'track_expiry')

    with op.batch_alter_table('sale_item_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_item_batches_sales_order_item_id'))
        batch_op.drop_index(batch_op.f('ix_sale_item_batches_organization_id'))
        batch_op.drop_index(batch_op.f('ix_sale_item_batches_batch_id'))

    op.drop_table('sale_item_batches')
    with op.batch_alter_table('batch_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_stock_organization_id'))
        batch_op.drop_index(batch_op.f('ix_batch_stock_branch_id'))
        batch_op.drop_index(batch_op.f('ix_batch_stock_batch_id'))

    op.drop_table('batch_stock')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_product_id'))
        batch_op.drop_index(batch_op.f('ix_batches_organization_id'))
        batch_op.drop_index('ix_batch_org_expiry')

    op.drop_table('batches')
    # ### end Alembic commands ###
