"""approval inbox: rules and requests

Revision ID: c2dbdeb880b7
Revises: 22338a3dc0df
Create Date: 2026-09-29 09:24:37.104269
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c2dbdeb880b7'
down_revision: Union[str, None] = '22338a3dc0df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.String(length=300), nullable=True),
    sa.Column('result_reference_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_requests_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_requested_by_user_id'), ['requested_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requests_status'), ['status'], unique=False)

    op.create_table('approval_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('approver_role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'kind')
    )
    with op.batch_alter_table('approval_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_rules_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###

    # Data migration: seed the default expense-approval rule for every organization
    # that existed before this revision (new ones are seeded at creation).
    import uuid
    from datetime import datetime, timezone

    from api.approvals import DEFAULT_RULES

    connection = op.get_bind()
    rules_table = sa.table(
        "approval_rules", sa.column("id", sa.String), sa.column("organization_id", sa.String),
        sa.column("kind", sa.String), sa.column("threshold", sa.Numeric), sa.column("approver_role", sa.String),
        sa.column("active", sa.Boolean), sa.column("created_at", sa.DateTime), sa.column("updated_at", sa.DateTime),
    )
    now = datetime.now(timezone.utc)
    org_ids = [row[0] for row in connection.execute(sa.text("SELECT id FROM organizations"))]
    rows = [
        {
            "id": str(uuid.uuid4()), "organization_id": org_id, "kind": kind, "threshold": threshold,
            "approver_role": approver_role, "active": True, "created_at": now, "updated_at": now,
        }
        for org_id in org_ids for kind, threshold, approver_role in DEFAULT_RULES
    ]
    if rows:
        connection.execute(rules_table.insert(), rows)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_rules_organization_id'))

    op.drop_table('approval_rules')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requests_status'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_requested_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_approval_requests_kind'))

    op.drop_table('approval_requests')
    # ### end Alembic commands ###
