"""measured_by on recommendation outcomes

Revision ID: c8cd4ad93c79
Revises: 3a9a82752387
Create Date: 2026-09-30 22:29:51.178459
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c8cd4ad93c79'
down_revision: Union[str, None] = '3a9a82752387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_outcomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measured_by', sa.String(length=12), server_default='manual', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_outcomes', schema=None) as batch_op:
        batch_op.drop_column('measured_by')

    # ### end Alembic commands ###
