"""stock take: counts and lines

Revision ID: d070d4b898b9
Revises: c6ec9372b08e
Create Date: 2026-09-29 15:58:51.741339
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd070d4b898b9'
down_revision: Union[str, None] = 'c6ec9372b08e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_counts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('started_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_counts_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_counts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_counts_started_at'), ['started_at'], unique=False)

    op.create_table('stock_count_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('stock_count_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('system_qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('counted_qty', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('counted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['stock_count_id'], ['stock_counts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_count_id', 'product_id')
    )
    with op.batch_alter_table('stock_count_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_count_lines_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_count_lines_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_count_lines_stock_count_id'), ['stock_count_id'], unique=False)

    # ### end Alembic commands ###

    # Data migration: seed the 5910 "Inventory Shrinkage/Adjustment" account for
    # every organization that existed before this revision (new ones get the
    # full chart, including this row, via api.accounting.seed_default_accounts).
    import uuid
    from datetime import datetime, timezone

    connection = op.get_bind()
    has_account = {row[0] for row in connection.execute(
        sa.text("SELECT organization_id FROM accounts WHERE code = '5910'"))}
    org_ids = [row[0] for row in connection.execute(sa.text("SELECT id FROM organizations"))]
    now = datetime.now(timezone.utc)
    accounts_table = sa.table(
        "accounts", sa.column("id", sa.String), sa.column("organization_id", sa.String),
        sa.column("code", sa.String), sa.column("name", sa.String), sa.column("type", sa.String),
        sa.column("is_system", sa.Boolean), sa.column("active", sa.Boolean),
        sa.column("created_at", sa.DateTime), sa.column("updated_at", sa.DateTime),
    )
    rows = [
        {
            "id": str(uuid.uuid4()), "organization_id": org_id, "code": "5910",
            "name": "Inventory Shrinkage/Adjustment", "type": "expense", "is_system": True,
            "active": True, "created_at": now, "updated_at": now,
        }
        for org_id in org_ids if org_id not in has_account
    ]
    if rows:
        connection.execute(accounts_table.insert(), rows)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_count_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_count_lines_stock_count_id'))
        batch_op.drop_index(batch_op.f('ix_stock_count_lines_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_count_lines_organization_id'))

    op.drop_table('stock_count_lines')
    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_counts_started_at'))
        batch_op.drop_index(batch_op.f('ix_stock_counts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_stock_counts_branch_id'))

    op.drop_table('stock_counts')
    # ### end Alembic commands ###
    op.execute("DELETE FROM accounts WHERE code = '5910'")
