"""auth credentials and recommendation loop

Revision ID: e61a9f46d478
Revises: 1db75e853483
Create Date: 2026-09-28 12:19:24.595506
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e61a9f46d478'
down_revision: Union[str, None] = '1db75e853483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('cutoff_date', sa.String(length=10), nullable=False),
    sa.Column('rank_in_rt', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('target_sku', sa.String(length=160), nullable=True),
    sa.Column('target_customer_id', sa.String(length=64), nullable=True),
    sa.Column('division', sa.String(length=60), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('benefit_bdt', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('action_cost_bdt', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('risk_bdt', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('utility_bdt', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('feasible', sa.Boolean(), nullable=False),
    sa.Column('infeasible_reason', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('explanation_json', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action_type in ('reorder','expiry','retention')", name='ck_reco_type'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index('ix_reco_org_cutoff', ['organization_id', 'cutoff_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_cutoff_date'), ['cutoff_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_run_id'), ['run_id'], unique=False)

    op.create_table('recommendation_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('modified_quantity', sa.Integer(), nullable=True),
    sa.Column('defer_until', sa.String(length=10), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision in ('accept','reject','modify','defer')", name='ck_decision'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_decision_org_time', ['organization_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_decisions_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_decisions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_decisions_recommendation_id'), ['recommendation_id'], unique=False)

    op.create_table('recommendation_outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_window_days', sa.Integer(), nullable=False),
    sa.Column('action_taken', sa.Boolean(), nullable=True),
    sa.Column('stockout_days_before', sa.Integer(), nullable=True),
    sa.Column('stockout_days_after', sa.Integer(), nullable=True),
    sa.Column('holding_cost_before_bdt', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('holding_cost_after_bdt', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expired_value_bdt', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('customer_responded', sa.Boolean(), nullable=True),
    sa.Column('predicted_quantity', sa.Integer(), nullable=True),
    sa.Column('realised_quantity', sa.Integer(), nullable=True),
    sa.Column('realised_benefit_bdt', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('drift_flag', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_outcomes', schema=None) as batch_op:
        batch_op.create_index('ix_outcome_org_time', ['organization_id', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_outcomes_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_outcomes_recommendation_id'), ['recommendation_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_version')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('recommendation_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_outcomes_recommendation_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_outcomes_organization_id'))
        batch_op.drop_index('ix_outcome_org_time')

    op.drop_table('recommendation_outcomes')
    with op.batch_alter_table('recommendation_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_decisions_recommendation_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_decisions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_decisions_decision'))
        batch_op.drop_index('ix_decision_org_time')

    op.drop_table('recommendation_decisions')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_run_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_cutoff_date'))
        batch_op.drop_index(batch_op.f('ix_recommendations_branch_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_action_type'))
        batch_op.drop_index('ix_reco_org_cutoff')

    op.drop_table('recommendations')
    # ### end Alembic commands ###
